backend:
  name: github
  repo: ja-bravo/Clifden-Lifeboat

media_folder: static/assets
public_folder: assets

collections:
  - name: news
    label: News
    folder: new
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }